### ISSUE TITLE
User interface design

### ISSUE THREAD

**Issue by sktw** [philip-brohan/transcription_methods_review#1]
I'm a volunteer on the Weather Rescue project - Ed Hawkins recently posted a link to your experiments with Textract. I've been experimenting with ways to improve the user interface for the transcriptions, and have built a [demo](https://sktw.github.io/weather-rescue-demo) site to test various ideas. We've been thinking about things like improving the layout of the image and data entry boxes, adding input validation, auto-formatting, keyboard shortcuts etc. The aim is to make the transcription process as frictionless as possible, in order to improve speed, accuracy and volunteer retention. 

Having reviewed a number of transcription projects, I was wondering whether you'd identified any features in the user interface design that were particularly effective?

On a different issue, have you done any analysis on how much redundancy (that is, the number of volunteer transcriptions per observation) is required to get an acceptable level of accuracy? Do all the case studies use a static number, or did any use an adaptive approach?

**Comment by philip-brohan** [comment]
Experiments on this sort of project are a bit frustrating because people are so variable - just about whatever you propose, some people will love it and others hate it.
But we have not done the systematic experiments on UI that you suggest. It'd be an interesting project for a human factors expert, but a lot of work.
My experience is that 2 transcribers are enough if both are project regulars and taking the job seriously. For beginners it depends on how easy the UI is. If many participants are not trying, you may need many more.
